# Generated by Django 5.2.7 on 2025-10-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("timezone", models.CharField(default="UTC", max_length=63)),
                (
                    "cycle_days",
                    models.IntegerField(default=5, help_text="Number of days in cycle (e.g., 5)"),
                ),
                (
                    "periods_per_day",
                    models.IntegerField(default=8, help_text="Number of periods per day (e.g., 8)"),
                ),
                (
                    "period_minutes",
                    models.IntegerField(default=50, help_text="Length of each period in minutes"),
                ),
                (
                    "recess_after_period",
                    models.IntegerField(
                        blank=True,
                        help_text="Period number after which recess occurs (null if no recess)",
                        null=True,
                    ),
                ),
                (
                    "lunch_window_start_period",
                    models.IntegerField(
                        default=4, help_text="Period number when lunch window starts (1-indexed)"
                    ),
                ),
                (
                    "lunch_window_span",
                    models.IntegerField(default=2, help_text="Number of periods in lunch window"),
                ),
                (
                    "default_teacher_daily_cap",
                    models.IntegerField(
                        default=3, help_text="Default max periods per teacher per day"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="core_school_name_f5e185_idx")],
            },
        ),
        migrations.CreateModel(
            name="RoomFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_features",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "code"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.IntegerField(help_text="Maximum number of students")),
                (
                    "features",
                    models.ManyToManyField(blank=True, related_name="rooms", to="core.roomfeature"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("grade", models.IntegerField(help_text="Grade level (e.g., 9, 10, 11, 12)")),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional attributes like IEP, ELL level, etc.",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "grade", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "predicate",
                    models.JSONField(
                        default=dict,
                        help_text="JSON predicate for selecting students (e.g., grade==9 or IEP==true)",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="core.school",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(blank=True, related_name="groups", to="core.student"),
                ),
            ],
            options={
                "ordering": ["school", "name"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "daily_teaching_cap",
                    models.IntegerField(
                        blank=True,
                        help_text="Max periods per day (overrides school default if set)",
                        null=True,
                    ),
                ),
                (
                    "available_mask",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional per-day/per-period availability restrictions",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "last_name", "first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="roomfeature",
            index=models.Index(fields=["school", "code"], name="core_roomfe_school__22d3cc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roomfeature",
            unique_together={("school", "code")},
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["school", "name"], name="core_room_school__770751_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("school", "name")},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["school", "grade"], name="core_studen_school__2f50b6_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "last_name", "first_name"], name="core_studen_school__6efecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["school", "name"], name="core_group_school__896ab9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("school", "name")},
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["school", "last_name", "first_name"], name="core_teache_school__e75cde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["email"], name="core_teache_email_0ea460_idx"),
        ),
    ]
