# Generated by Django 5.2.7 on 2025-10-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="max_sections",
            field=models.IntegerField(
                default=3, help_text="Maximum number of unique sections this teacher can teach"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Subject area (e.g., Math, English, Science, History, PE)",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["school", "subject"], name="core_teache_school__595b6b_idx"),
        ),
    ]
