# Generated by Django 5.2.7 on 2025-10-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(help_text="Course code (e.g., ENG9)", max_length=50)),
                ("name", models.CharField(max_length=255)),
                (
                    "duration_periods",
                    models.IntegerField(
                        default=1, help_text="Number of consecutive periods per meeting"
                    ),
                ),
                (
                    "meets_per_week",
                    models.IntegerField(help_text="Number of times course meets per week"),
                ),
                (
                    "is_lab",
                    models.BooleanField(default=False, help_text="Whether this is a lab course"),
                ),
                ("capacity", models.IntegerField(help_text="Maximum students per section")),
                (
                    "base_course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Base course if this is a lab",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labs",
                        to="timetable.course",
                    ),
                ),
                (
                    "room_feature_required",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required room feature (e.g., LAB)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="core.roomfeature",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "code"],
            },
        ),
        migrations.CreateModel(
            name="RequirementTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "selector",
                    models.JSONField(
                        default=dict,
                        help_text="JSON predicates for which students this applies to (e.g., grade==9)",
                    ),
                ),
                (
                    "required_courses",
                    models.JSONField(
                        default=list,
                        help_text="List of required courses (e.g., [{course_code: 'ENG9', count: 1}])",
                    ),
                ),
                (
                    "lab_policy",
                    models.JSONField(
                        default=dict,
                        help_text="Lab policy (e.g., {course_code: 'SCI9', min_labs: 1, max_labs: 2})",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_templates",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "name"],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Immutable snapshot of configuration for this scenario",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("RUNNING", "Running"),
                            ("SOLVED", "Solved"),
                            ("INFEASIBLE", "Infeasible"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("logs", models.TextField(blank=True, help_text="Solver logs and diagnostics")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planned_count_per_week",
                    models.IntegerField(
                        help_text="Number of times this section should be scheduled per week"
                    ),
                ),
                (
                    "lock_to_periods",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional admin locks (e.g., {day: 1, period: 3})",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="timetable.course",
                    ),
                ),
                (
                    "room_candidates",
                    models.ManyToManyField(
                        help_text="Rooms where this section can be held",
                        related_name="candidate_sections",
                        to="core.room",
                    ),
                ),
                (
                    "teacher_candidates",
                    models.ManyToManyField(
                        help_text="Teachers who can teach this section",
                        related_name="candidate_sections",
                        to="core.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["course"],
            },
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.IntegerField(help_text="Day number (0-indexed)")),
                ("period", models.IntegerField(help_text="Period number (0-indexed)")),
                ("is_lab", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="core.room",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="core.teacher",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="timetable.scenario",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="timetable.section",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario", "day", "period"],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.IntegerField(help_text="Day number (0-indexed)")),
                ("period", models.IntegerField(help_text="Period number (0-indexed)")),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="timetable.scenario",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="timetable.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario", "student", "day", "period"],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["school", "code"], name="timetable_c_school__112b58_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["school", "is_lab"], name="timetable_c_school__fb753e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("school", "code")},
        ),
        migrations.AddIndex(
            model_name="requirementtemplate",
            index=models.Index(fields=["school", "name"], name="timetable_r_school__1d27c3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="requirementtemplate",
            unique_together={("school", "name")},
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(fields=["school", "status"], name="timetable_s_school__dc3f7f_idx"),
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(fields=["-created_at"], name="timetable_s_created_de1d63_idx"),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(
                fields=["scenario", "day", "period"], name="timetable_p_scenari_46f272_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(
                fields=["scenario", "teacher"], name="timetable_p_scenari_e18105_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(fields=["scenario", "room"], name="timetable_p_scenari_18c12c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="placement",
            unique_together={("scenario", "section", "day", "period")},
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["scenario", "student"], name="timetable_s_scenari_907b3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["scenario", "section"], name="timetable_s_scenari_393798_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["scenario", "day", "period"], name="timetable_s_scenari_c32970_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("scenario", "student", "day", "period")},
        ),
    ]
