# Generated by Django 5.2.7 on 2025-10-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="placement",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(
                fields=["scenario", "section"], name="timetable_p_scenari_16d392_idx"
            ),
        ),
    ]
