# Generated by Django 5.2.7 on 2025-10-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_alter_placement_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["course", "section_number"]},
        ),
        migrations.AddField(
            model_name="section",
            name="section_number",
            field=models.IntegerField(
                default=1,
                help_text="Section number (e.g., 1, 2, 3 for multiple sections of same course)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("course", "section_number")},
        ),
    ]
